name: autodo
description: Car Maintenance Made Simple.
version: 0.3.2+16
db_version: 3
authors:
  - Jonathan Bayless <baylessjonathan@gmail.com>
  - David PHAM-VAN <dev.nfet.net@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  json_intl:
  cloud_firestore:
  firebase_analytics:
  firebase_auth:
  shared_preferences:
  flutter_typeahead:
  flutter_local_notifications:
  url_launcher:
  charts_flutter:
  sliding_up_panel:
  bloc:
  flutter_bloc:
  google_sign_in:
  equatable:
  font_awesome_flutter:
  autocomplete_textfield:
  sentry:
  sembast:
  path_provider:
  firebase_admob:
  in_app_purchase:
  semaphore:
  provider:
  pref:
  cupertino_icons:
  about:
  cached_network_image:
  firebase_storage:
  image_picker:
  dotted_border:
  flutter_debug_drawer:
  animations:

dependency_overrides:
  flutter_debug_drawer:
    git:
      url: git://github.com/DavBfr/flutter_debug_drawer.git
      ref: master
  autocomplete_textfield:
    git:
      url: git://github.com/baylessj/flutter-autocomplete-textfield.git
      ref: master
  firebase_core: 0.4.4
  firebase_admob:
    git:
      url: git://github.com/autodo-app/flutterfire.git
      ref: master
      path: packages/firebase_admob/
  mockito: ^4.0.0
  bloc_test: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  bloc_test:
  mockito:
  pedantic:
  pubspec_extract:
  image_test_utils:

flutter:
  uses-material-design: true

  assets:
    - img/logo.png
    - img/icon.png
    - img/icon-only.png
    - img/icon-only-green.png
    - legal/privacy-policy.md
    - assets/intl/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu/Ubuntu-B.ttf
          weight: 800
        - asset: fonts/ubuntu/Ubuntu-BI.ttf
          weight: 800
          style: italic
        - asset: fonts/ubuntu/Ubuntu-L.ttf
          weight: 300
        - asset: fonts/ubuntu/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: fonts/ubuntu/Ubuntu-M.ttf
          weight: 600
          style: normal
        - asset: fonts/ubuntu/Ubuntu-MI.ttf
          weight: 600
          style: italic
        - asset: fonts/ubuntu/Ubuntu-R.ttf
          weight: 400
          style: italic
        - asset: fonts/ubuntu/Ubuntu-RI.ttf
          weight: 400
          style: italic
        - asset: fonts/ubuntu/Ubuntu-Th.ttf
          weight: 900
