# https://medium.com/better-programming/ci-cd-for-flutter-apps-using-github-actions-b833f8f7aac
on: push
name: Build
jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - run: flutter pub get
    - run: echo "${{ secrets.keys_json }}" > assets/keys.json
    - run: echo "${{ secrets.store_file }}" | base64 --decode > ~/keystore.jks
    - run: echo "${{ secrets.google_services }}" | base64 --decode > ./android/app/google-services.json
    - run: flutter build apk --debug --split-per-abi
      env:
        KEY_ALIAS: ${{ secrets.key_alias }}
        KEY_PASSWORD: ${{ secrets.key_password }}
        STORE_FILE: ~/keystore.jks
        STORE_PASSWORD: ${{ secrets.store_password }}
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - run: flutter pub get
    - run: echo "${{ secrets.keys_json }}" > assets/keys.json
    - run: echo "${{ secrets.store_file }}" | base64 --decode > ~/keystore.jks
    - run: echo "${{ secrets.google_services }}" | base64 --decode > ./android/app/google-services.json
    - run: echo "${{ secrets.google_services_plist }}" > /Users/runner/runners/2.164.0/work/autodo/autodo/ios/GoogleService-Info.plist
    - run: echo "${{ secrets.info_plist }}" > /Users/runner/runners/2.164.0/work/autodo/autodo/ios/Runner/Info.plist
    - run: flutter build ios --release --no-codesign
      env:
        KEY_ALIAS: ${{ secrets.key_alias }}
        KEY_PASSWORD: ${{ secrets.key_password }}
        STORE_FILE: ~/keystore.jks
        STORE_PASSWORD: ${{ secrets.store_password }}